apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-lib
spec:
  replicas: 1  # Valeur par défaut, ajustée par la commande de mise à l'échelle
  selector:
    matchLabels:
      app: books-lib
  template:
    metadata:
      labels:
        app: books-lib
    spec:
      containers:
      - name: books-lib
        image: moseskapend/book_store_appweb:latest
        ports:
        - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: books-lib-service
spec:
  selector:
    app: books-lib
  type: NodePort
  ports:
  - port: 80
    targetPort: 8000 
    nodePort: 32043