apiVersion: v1
kind: Secret
metadata:
  name: mysql-db-secret
type: Opaque
data:
  root-password: cm9vdA== 

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-db-config
data:
  MYSQL_ROOT_HOST: '%'
  MYSQL_DATABASE: 'books'
  my.cnf: |
    [mysqld]
    lower_case_table_names=1