version: '3.1'

services:
  bdd:
    image: mysql:latest
    container_name: mysqlserver
    restart: always
    environment:
      - MYSQL_DATABASE=books
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root 
    ports:
      - '3306:3306'
    volumes:
      - ./mysql_data:/var/lib/mysql

  appweb:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "sleep 45 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    depends_on:
      - bdd
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://bdd:3306"]
      interval: 10s
      retries: 5

volumes:
  mysql_data: