version: "3.7"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: livrebymoses
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq

  celery:
    build: .
    command: celery -A LivreByMoses worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - db
      - rabbitmq
