apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
spec:
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django
          image: moseskapend/livrebymoses
          ports:
            - containerPort: 8000
          env:
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_DATABASE
              value: "livrebymoses"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              value: "password"
---
apiVersion: v1
kind: Service
metadata:
  name: django
spec:
  ports:
    - port: 8000
  selector:
    app: django
