# Generated by Django 4.2.11 on 2024-07-15 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0002_remove_livre_clients_alter_livre_prix_commande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='email_client',
        ),
        migrations.AddField(
            model_name='commande',
            name='client',
            field=models.ForeignKey(default='01', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
