# Generated by Django 4.2.11 on 2024-07-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_commande_email_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='email_client',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='commande',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='livre',
            name='auteur',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='livre',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
