apiVersion: apps/v1
kind: Deployment
metadata:
  name: jo-ges
spec:
  replicas: 1  # Valeur par défaut, ajustée par la commande de mise à l'échelle
  selector:
    matchLabels:
      app: jo-ges
  template:
    metadata:
      labels:
        app: jo-ges
    spec:
      containers:
      - name: jo-ges
        image: moseskapend/myfirst_web:latest
        ports:
        - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: jo-ges-service
spec:
  selector:
    app: jo-ges
  type: NodePort
  ports:
  - port: 80  # Port externe exposé par le service
    targetPort: 8000  # Port sur les pods vers lequel le trafic est acheminé
    nodePort: 32043