# Generated by Django 4.2.11 on 2024-07-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_commande_email_client_commande_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='email_client',
            field=models.EmailField(default='2', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commande',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
