# Generated by Django 4.2.11 on 2024-07-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_commande_email_client_commande_prix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='email_client',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
    ]
